# Generated by Django 4.2.2 on 2023-11-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0002_policeprofile_first_name_policeprofile_las_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
