# Generated by Django 4.2.2 on 2023-11-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0003_policeprofile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policeprofile',
            old_name='las_name',
            new_name='last_name',
        ),
    ]
