# Generated by Django 4.2.2 on 2023-11-21 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('me', '0005_delete_citizenprofile_delete_policeprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policeprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CitizenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ghana_card_id', models.CharField(blank=True, max_length=30, null=True)),
                ('ghana_card_image_front', models.ImageField(blank=True, null=True, upload_to='ghana_card_frontImage/')),
                ('ghana_card_image_back', models.ImageField(blank=True, null=True, upload_to='ghana_card_backImage/')),
                ('drivers_linence_id', models.CharField(blank=True, max_length=10, null=True)),
                ('driver_linence_Image_front', models.ImageField(blank=True, null=True, upload_to='drivers_linence_Image/')),
                ('postal_address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
