# Generated by Django 4.2.2 on 2023-11-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenprofile',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
