# Generated by Django 4.2.2 on 2023-11-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0007_citizenprofile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizenprofile',
            old_name='driver_linence_Image_front',
            new_name='driver_license_Image_front',
        ),
        migrations.RenameField(
            model_name='citizenprofile',
            old_name='drivers_linence_id',
            new_name='drivers_license_id',
        ),
    ]
