# Generated by Django 4.2.2 on 2023-11-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0010_alter_citizenprofile_user_alter_policeprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complains',
            name='citizen',
        ),
        migrations.RemoveField(
            model_name='complains',
            name='description',
        ),
        migrations.AddField(
            model_name='complains',
            name='citizens',
            field=models.ManyToManyField(to='me.citizenprofile'),
        ),
        migrations.AlterField(
            model_name='citizenprofile',
            name='ghana_card_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
