# Generated by Django 4.2.2 on 2023-11-25 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0011_remove_complains_citizen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complains',
            name='citizens',
        ),
        migrations.AddField(
            model_name='complains',
            name='citizens',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='me.citizenprofile'),
        ),
    ]
