# Generated by Django 4.2.2 on 2023-11-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0013_alter_policeprofile_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policeprofile',
            name='service_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
