# Generated by Django 4.2.2 on 2023-12-03 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0014_alter_policeprofile_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complains',
            name='citizens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='me.citizenprofile'),
        ),
    ]
