# Generated by Django 4.2.2 on 2023-12-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0015_alter_complains_citizens'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenprofile',
            name='email',
            field=models.EmailField(default=True, max_length=254, null=True),
        ),
    ]
