# Generated by Django 4.2.2 on 2023-12-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0015_alter_complains_citizens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenprofile',
            name='driver_license_Image_front',
            field=models.ImageField(blank=True, null=True, upload_to='drivers_license_Image/'),
        ),
    ]
