# Generated by Django 4.2.2 on 2023-12-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0016_alter_citizenprofile_driver_license_image_front'),
        ('me', '0016_citizenprofile_email'),
    ]

    operations = [
    ]
