# Generated by Django 4.2.2 on 2023-12-15 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0018_remove_complains_fine_paid_complains_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complains',
            name='citizens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='me.citizenprofile'),
        ),
        migrations.AlterField(
            model_name='complains',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.policeprofile'),
        ),
    ]
